Write a program that uses a print function to say 'hello world' as shown in 'Desired Output'.

In [1]:
print("Hello, World")

Hello, World


2.2 Write a program that uses input to prompt a user for their name and then welcomes them. Note that input will pop up a dialog box. Enter Sarah in the pop-up box when you are prompted so your output will match the desired output.

In [2]:
name = input("Enter your name")
print("Hello", name)

Enter your name Sarah


Hello Sarah


2.3 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking or bad user data.

In [4]:
hours = input("Enter Hours: ")
rate = input("Enter Rate: ",)
payment = float(hours) * float(rate)
print("Pay:",payment)

Enter Hours:  35
Enter Rate:  2.75


Pay: 96.25


3.1 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.

In [5]:
hrs = input("Enter Hours:")
h = float(hrs)
rate = input("Rate:")
r = float(rate)

if h <= 40:
    regular_pay = h * r
else:
    regular_pay = 40 * r
    overtime_hours = h - 40
    overtime_pay = overtime_hours * r * 1.5
    gross_pay = regular_pay + overtime_pay
print(gross_pay)

Enter Hours: 45
Rate: 10.50


498.75


3.2 rewrite of exercise 3.1

In [7]:
hrs = input("Enter Hours:")
rate = input("Rate:")

try:
    h = float(hrs)
    r = float(rate)
except:
    print("Error, please enter numeric input")
    quit()

if h <= 40:
    regular_pay = h * r
else:
    regular_pay = 40 * r
    overtime_hours = h - 40
    overtime_pay = overtime_hours * r * 1.5
    gross_pay = regular_pay + overtime_pay
print(gross_pay)

Enter Hours: 45
Rate: 10.50


498.75


3.3 Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
Score Grade
-  \>= 0.9 A
-  >= 0.8 B
-  >= 0.7 C
-  >= 0.6 D
-  < 0.6 F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.

In [6]:
score = input("Enter Score: ")

try:
    score = float(score)
    if score >= 0.0 and score <= 1.0:
        if score >= 0.9:
            print("A")
        elif score >= 0.8:
            print("B")
        elif score >= 0.7:
            print("C")
        elif score >= 0.6:
         print("D")
        else:
            print(score, "F")
    else:
        print("Error: score is out or range")
except:
    print("Please enter a number between 0.0 and 1.0")

Enter Score:  0.85


B


4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.

In [8]:
def computepay(h, r):
    if h <= 40:
        regular_pay = h * r
    else:
        regular_pay = 40 * r
        overtime_hours = h - 40
        overtime_pay = overtime_hours * r * 1.5
        gross_pay = regular_pay + overtime_pay
    return gross_pay

hrs = input("Enter Hours:")
rate = input("Rate:")
try:
    h = float(hrs)
    r = float(rate)
except:
    print("Error, please enter numeric input")
    quit()

p = computepay(h, r)
print("Pay", p)

Enter Hours: 45
Rate: 10.50


Pay 498.75


Exercise 1: Write a program which repeatedly reads integers until the user enters “done”. Once “done” is entered, print out the total, count, and average of the integers. If the user enters anything other than a integers, detect their mistake using try and except and print an error message and skip to the next integers.

In [1]:
num = 0
total = 0.0
while True:
    sval = input('Enter a number: ')
    if sval == 'done':
        break
    try:
        fval = float(sval)
    except:
        print('Invalid input')
        continue
    num = num + 1
    total = total + fval
print('All done')
print(total, num, total/num)

Enter a number:  23
Enter a number:  76
Enter a number:  23
Enter a number:  done


All done
122.0 3 40.666666666666664


5.2 Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.

In [2]:
largest = None
smallest = None
while True:
    sval = input('Enter a number: ')
    if sval == 'done':
        break
    try:
        fval = int(sval)
    except:
        print('Invalid input')
        continue
    if largest is None or fval > largest:
        largest = fval
    if smallest is None or fval < smallest:
        smallest = fval
print('Maximum is', largest)
print('Minimum is', smallest)

Enter a number:  dfd


Invalid input


Enter a number:  223
Enter a number:  bob


Invalid input


Enter a number:  34
Enter a number:  done


Maximum is 223
Minimum is 34


7.1 Write a program that prompts for a file name, then opens that file and reads through the file, and print the contents of the file in upper case. Use the file words.txt to produce the output below.
You can download the sample data at http://www.py4e.com/code3/words.txt

In [12]:
# Use words.txt as the file name
fname = input("Enter file name: ")
fh = open(fname)
for line in fh:
    line = line.rstrip()
    print(line.upper())

Enter file name:  words.txt


WRITING PROGRAMS OR PROGRAMMING IS A VERY CREATIVE
AND REWARDING ACTIVITY  YOU CAN WRITE PROGRAMS FOR
MANY REASONS RANGING FROM MAKING YOUR LIVING TO SOLVING
A DIFFICULT DATA ANALYSIS PROBLEM TO HAVING FUN TO HELPING
SOMEONE ELSE SOLVE A PROBLEM  THIS BOOK ASSUMES THAT
{\EM EVERYONE} NEEDS TO KNOW HOW TO PROGRAM AND THAT ONCE
YOU KNOW HOW TO PROGRAM, YOU WILL FIGURE OUT WHAT YOU WANT
TO DO WITH YOUR NEWFOUND SKILLS

WE ARE SURROUNDED IN OUR DAILY LIVES WITH COMPUTERS RANGING
FROM LAPTOPS TO CELL PHONES  WE CAN THINK OF THESE COMPUTERS
AS OUR PERSONAL ASSISTANTS WHO CAN TAKE CARE OF MANY THINGS
ON OUR BEHALF  THE HARDWARE IN OUR CURRENT-DAY COMPUTERS
IS ESSENTIALLY BUILT TO CONTINUOUSLY ASK US THE QUESTION
WHAT WOULD YOU LIKE ME TO DO NEXT

OUR COMPUTERS ARE FAST AND HAVE VASTS AMOUNTS OF MEMORY AND
COULD BE VERY HELPFUL TO US IF WE ONLY KNEW THE LANGUAGE TO
SPEAK TO EXPLAIN TO THE COMPUTER WHAT WE WOULD LIKE IT TO
DO NEXT IF WE KNEW THIS LANGUAGE WE COULD TELL THE
COMPUTER TO DO TASKS 

7.2 Write a program that prompts for a file name, then opens that file and reads through the file, looking for lines of the form:
X-DSPAM-Confidence:    0.8475
Count these lines and extract the floating point values from each of the lines and compute the average of those values and produce an output as shown below. Do not use the sum() function or a variable named sum in your solution.
You can download the sample data at http://www.py4e.com/code3/mbox-short.txt when you are testing below enter mbox-short.txt as the file name.

In [1]:
# Use the file name mbox-short.txt as the file name
fname = input("Enter file name: ")
fh = open(fname)
count = 0
total = 0.0
for line in fh:
    if not line.startswith("X-DSPAM-Confidence:"):
        continue
    # Remove leading/trailing whitespace including newline character
    line = line.rstrip()
    # Split the line into words
    fields = line.split()
    # The second word is the confidence value
    confidence = fields[1]
    # Convert the confidence value to a floating point number
    fconfidence = float(confidence)
    # Update count and total
    count = count + 1
    total = total + fconfidence
    # Calculate and print the average
    average = total / count
print("Average spam confidence:", average)

Enter file name:  mbox-short.txt


Average spam confidence: 0.7507185185185187


Use the file name mbox-short.txt as the file name
fname = input("Enter file name: ")
fh = open(fname)
count = 0
total = 0.0
for line in fh:
    if not line.startswith("X-DSPAM-Confidence:"):
        continue
    # Remove leading/trailing whitespace including newline character
    line = line.rstrip()
    # Split the line into words
    fields = line.split()
    # The second word is the confidence value
    confidence = fields[1]
    # Convert the confidence value to a floating point number
    fconfidence = float(confidence)
    # Update count and total
    count = count + 1
    total = total + fconfidence
    # Calculate and print the average
    average = total / count
print("Average spam confidence:", average)

8.4 Open the file romeo.txt and read it line by line. For each line, split the line into a list of words using the split() method. The program should build a list of words. For each word on each line check to see if the word is already in the list and if not append it to the list. When the program completes, sort and print the resulting words in python sort() order as shown in the desired output.
You can download the sample data at http://www.py4e.com/code3/romeo.txt

In [2]:
fname = input("Enter file name: ")
fh = open(fname)
lst = list()
for line in fh:
    line = line.rstrip()
    words = line.split()
    for word in words:
        if word not in lst:
            lst.append(word)
lst.sort()
print(lst)

Enter file name:  romeo.txt


['Arise', 'But', 'It', 'Juliet', 'Who', 'already', 'and', 'breaks', 'east', 'envious', 'fair', 'grief', 'is', 'kill', 'light', 'moon', 'pale', 'sick', 'soft', 'sun', 'the', 'through', 'what', 'window', 'with', 'yonder']


8.5 Open the file mbox-short.txt and read it line by line. When you find a line that starts with 'From ' like the following line:
From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
You will parse the From line using split() and print out the second word in the line (i.e. the entire address of the person who sent the message). Then print out a count at the end.
Hint: make sure not to include the lines that start with 'From:'. Also look at the last line of the sample output to see how to print the count.

You can download the sample data at http://www.py4e.com/code3/mbox-short.txt

In [2]:
fname = input("Enter file name: ")
if len(fname) < 1:
    fname = "mbox-short.txt"

fh = open(fname)
count = 0
for line in fh:
    line = line.rstrip()
    if line.startswith("From "):
        words = line.split()
        print(words[1])
        count += 1
        
print("There were", count, "lines in the file with From as the first word")

Enter file name:  


stephen.marquard@uct.ac.za
louis@media.berkeley.edu
zqian@umich.edu
rjlowe@iupui.edu
zqian@umich.edu
rjlowe@iupui.edu
cwen@iupui.edu
cwen@iupui.edu
gsilver@umich.edu
gsilver@umich.edu
zqian@umich.edu
gsilver@umich.edu
wagnermr@iupui.edu
zqian@umich.edu
antranig@caret.cam.ac.uk
gopal.ramasammycook@gmail.com
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
stephen.marquard@uct.ac.za
louis@media.berkeley.edu
louis@media.berkeley.edu
ray@media.berkeley.edu
cwen@iupui.edu
cwen@iupui.edu
cwen@iupui.edu
There were 27 lines in the file with From as the first word
